const MIN_NAME_LENGTH = 5;
const MAX_NAME_LENGTH = 20;
const MIN_EMAIL_LENGTH = 5;
const MAX_EMAIL_LENGTH = 255;
const MIN_PASSWORD_LENGTH = 5;
const MAX_PASSWORD_LENGTH = 255;

module.exports = {
  MIN_NAME_LENGTH,
  MAX_NAME_LENGTH,
  MIN_EMAIL_LENGTH,
  MAX_EMAIL_LENGTH,
  MIN_PASSWORD_LENGTH,
  MAX_PASSWORD_LENGTH,
};
